### ISSUE TITLE
org.openqa.selenium.WebDriverException: arguments[0] is undefined

### ISSUE THREAD

**Issue by G1yyK** [codeborne/selenide#159]
Это весь тест, как только делаю setValue вываливается ошибка(ниже), скорей всего ошипка появляется при выполнении js когда в input попадают данные.

open("http://ya.ru/");
$(By.id("text")).setValue("asdfasdfasdfasdf");

org.openqa.selenium.WebDriverException: arguments[0] is undefined
Command duration or timeout: 958 milliseconds
Build info: version: '2.44.0', revision: '76d78cf323ce037c5f92db6c1bba601c2ac43ad8', time: '2014-10-23 13:11:40'
System info: host: 'g1yyk', ip: '127.0.0.1', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.4', java.version: '1.7.0_51'
Session ID: 286f4bc2-da96-7447-aea0-2ea54becba7e
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=MAC, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=35.0.1}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:508)
	at com.codeborne.selenide.Selenide.executeJavaScript(Selenide.java:308)
	at com.codeborne.selenide.impl.AbstractSelenideElement.fireEvent(AbstractSelenideElement.java:402)
	at com.codeborne.selenide.impl.AbstractSelenideElement.fireChangeEvent(AbstractSelenideElement.java:376)
	at com.codeborne.selenide.impl.AbstractSelenideElement.setValue(AbstractSelenideElement.java:370)
	at com.codeborne.selenide.impl.AbstractSelenideElement.dispatch(AbstractSelenideElement.java:67)
	at com.codeborne.selenide.impl.AbstractSelenideElement.invoke(AbstractSelenideElement.java:55)
	at com.codeborne.selenide.impl.WaitingSelenideElement.invoke(WaitingSelenideElement.java:19)
	at com.sun.proxy.$Proxy4.setValue(Unknown Source)
	at tests.TestIntegration.mainTest(TestIntegration.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: org.openqa.selenium.WebDriverException: arguments[0] is undefined
Build info: version: '2.44.0', revision: '76d78cf323ce037c5f92db6c1bba601c2ac43ad8', time: '2014-10-23 13:11:40'
System info: host: 'g1yyk', ip: '127.0.0.1', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.4', java.version: '1.7.0_51'
Driver info: driver.version: unknown
	at <anonymous class>.anonymous(http://ya.ru/ line 68 > Function:8:11)
	at <anonymous class>.handleEvaluateEvent(http://ya.ru/:68:20)

**Comment by dengayevskiy** [comment]
В каком браузере запускаете? Если FF35, то нужно вернуться на 34 версию и все заработает.

**Comment by G1yyK** [comment]
Спасибо.

**Comment by asolntsev** [comment]
Ух ты, про версию FireFox ничего не знаю. На самом деле в методе `$.setValue` была бага. Она была исправлена в последней версии Selenide 2.16. Вы какую версию используете?

**Comment by dengayevskiy** [comment]
А я про багу ничего не знал) Использую 2.16 и после обновления до FF35 тоже стала появляться такая ошибка. Это связано с тем, что Селениум и ФФ апдейтятся не согласованно и новые версии ФФ часто не совместимы с актуальной версией селениума. Как-то так.

**Comment by cpomp** [comment]
I used google translate to figure out you comments :)
asolntev is right it has nothing to do with selenide is related to selenium 2.44.0 not being able to support FF 35
https://selenium.googlecode.com/git/java/CHANGELOG

Just download the latest supported FF 33 and your test will start to run again
https://ftp.mozilla.org/pub/mozilla.org/firefox/releases/

**Comment by asolntsev** [comment]
Thank you, cpomp! You are right, the problem is with FireFox 35. I have downgraded FireFox to 34.0.5 in build-server, and now all the tests are green again.
