### ISSUE TITLE
IE + site w cert error is not working with selenide

### ISSUE THREAD

**Issue by asolntsev** [codeborne/selenide#161]
[Enrique]

To reproduce:
-          Use the “com.codeborne.selenide.Selenide.open” method to go to any site that wil produce a “there is a problem with this website’s security certificate” warning page

 
Notice that the following expection will be trown:

```java
org.openqa.selenium.WebDriverException: JavaScript error (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 78 milliseconds
Build info: version: '2.42.2', revision: '6a6995d31c7c56c340d6f45a76976d43506cd6cc', time: '2014-06-03 10:52:47'
System info: host: 'L-103957-P14', ip: '172.22.99.3', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
selenide.url: https://10.198.207.243/simplesaml/testVipLogin/setSSOparams.html
Capabilities [{browserAttachTimeout=0, enablePersistentHover=true, ie.forceCreateProcessApi=false, ie.usePerProcessProxy=false, ignoreZoomSetting=true, handlesAlerts=true, version=9, platform=WINDOWS, nativeEvents=true, ie.ensureCleanSession=false, elementScrollBehavior=0, ie.browserCommandLineSwitches=, requireWindowFocus=false, browserName=internet explorer, initialBrowserUrl=http://localhost:2637/, takesScreenshot=true, javascriptEnabled=true, ignoreProtectedModeSettings=true, enableElementCacheCleanup=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=dismiss}]
selenide.baseUrl: http://localhost:8080
Session ID: eeeb3c8b-1514-4ce7-a562-4dc31cddc6eb
                at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
                at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
                at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
                at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
                at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
                at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:508)
                at com.codeborne.selenide.impl.Navigator.collectJavascriptErrors(Navigator.java:48)
                at com.codeborne.selenide.impl.Navigator.navigateToAbsoluteUrl(Navigator.java:39)
                at com.codeborne.selenide.impl.Navigator.open(Navigator.java:17)
                at com.codeborne.selenide.Selenide.open(Selenide.java:48)
                at com.codeborne.selenide.Selenide.open(Selenide.java:81)
                at com.symantec.vipLogin.tests.BaseTest.openSignInPage(BaseTest.java:69)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:483)
                at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
                at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
                at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
                at org.testng.internal.Invoker.invokeMethod(Invoker.java:653)
                at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
                at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
                at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
                at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
                at org.testng.TestRunner.privateRun(TestRunner.java:767)
                at org.testng.TestRunner.run(TestRunner.java:617)
                at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
                at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
                at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
                at org.testng.SuiteRunner.run(SuiteRunner.java:240)
                at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
                at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
                at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
                at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
                at org.testng.TestNG.run(TestNG.java:1057)
                at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
                at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
                at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
 ```

The exception gets thrown when this line is executed: `com.codeborne.selenide.impl.Navigator.collectJavascriptErrors(Navigator.java:48)`

The usual workaround is to execute this line once you are on that warning page:
`driver.navigate().to("javascript:document.getElementById('overridelink').click()");`
 
However, the `Selenide.open` call is creating the driver so I don’t have one to use at this point. I could precreate one myself and execute the javascript but that would completely negate my effort of writing the WebDriverFactory class that implements “WebDriverProvider”
 
Is there a workaround for this?

**Comment by asolntsev** [comment]
As a workaround, you can override method 
`com.codeborne.selenide.impl.Navigator.collectJavascriptErrors()`

I will investigate how to create a better solution.

**Comment by asolntsev** [comment]
I hope it's now fixed in Selenide 2.19
Thought, the workaround `driver.navigate().to("javascript:document.getElementById('overridelink').click()");` did not work for me. :(

**Comment by simple-elf** [comment]
There is no problem to open page with certificate error. But selenide can't click on link with id 'overridelink'. Any other solutions to send javascript code to webdriver by using Selenide?

**Comment by simple-elf** [comment]
Just finded method "executeJavaScript" but it won't work on grid IE nodes (because of selenium bug)

**Comment by rodionovsasha** [comment]
I use selenide 3.4 and have the same issue:
com.codeborne.selenide.Selenide getJavascriptErrors
SEVERE: org.openqa.selenium.WebDriverException: JavaScript error (WARNING: The server did not provide any stacktrace information)

Is it planning to fix? What is correct way to override com.codeborne.selenide.impl.Navigator.collectJavascriptErrors?

**Comment by asolntsev** [comment]
We tried to design Selenide so that you can override every single method.
In this case, you can override method `Navigator.collectJavascriptErrors()` like that:

```java
Selenide.navigator = new Navigator() {
  @Override
  protected void collectJavascriptErrors(JavascriptExecutor webdriver) {
    // do nothing
  }
};
```

**Comment by rodionovsasha** [comment]
Thank you Andrey
