### ISSUE TITLE
Element has given class, but exception is thrown

### ISSUE THREAD

**Issue by dmak** [codeborne/selenide#162]
With Selenide v2.16 I get sometimes (say, 1 of 10 runs) the following error:

    com.codeborne.selenide.ex.ElementShould: Element should css class 'done' {#tab-area li[aria-controls='help']}
    Element: '<li aria-controls="help" class="ui-state-default ui-corner-top ui-tabs-active ui-state-active done">Help</li>'
    Screenshot: file:/test/workspace/target/selenide-reports/1423759389953.0.png
    Timeout: 10 s.
    	at com.codeborne.selenide.impl.AbstractSelenideElement.waitUntil(AbstractSelenideElement.java:596)
    	at com.codeborne.selenide.impl.AbstractSelenideElement.waitUntil(AbstractSelenideElement.java:557)
    	at com.codeborne.selenide.impl.AbstractSelenideElement.dispatch(AbstractSelenideElement.java:193)
    	at com.codeborne.selenide.impl.AbstractSelenideElement.invoke(AbstractSelenideElement.java:55)
    	at com.codeborne.selenide.impl.WaitingSelenideElement.invoke(WaitingSelenideElement.java:19)
    	at com.sun.proxy.$Proxy6.waitUntil(Unknown Source)
    	at test.CommonUtils.waitForPanelToLoad(CommonUtils.java:134)

The point is that element has class `done` (as reported in exception), but still `ElementShould` is thrown.

**Comment by asolntsev** [comment]
I guess it happens when `done` class appears **exactly** after 10 seconds. There is no other cure but enlarging timeout or optimizing performance of your application.

**Comment by dmak** [comment]
I have example of exactly the same problem in Selenide v2.22, this time with `textCaseSensitive()` condition:
```
com.codeborne.selenide.ex.ElementShould: Element should have textCaseSensitive '09000525 FD: 1999-11-08' {.timeline-event-bubble-title}
Element: '<div class="timeline-event-bubble-title">09000525 FD: 1999-11-08</div>'
	at com.codeborne.selenide.impl.AbstractSelenideElement.checkCondition(AbstractSelenideElement.java:512)
	at com.codeborne.selenide.impl.AbstractSelenideElement.should(AbstractSelenideElement.java:476)
	at com.codeborne.selenide.impl.AbstractSelenideElement.invokeShould(AbstractSelenideElement.java:299)
	at com.codeborne.selenide.impl.AbstractSelenideElement.dispatchSelenideMethod(AbstractSelenideElement.java:179)
	at com.codeborne.selenide.impl.AbstractSelenideElement.dispatchAndRetry(AbstractSelenideElement.java:92)
	at com.codeborne.selenide.impl.AbstractSelenideElement.invoke(AbstractSelenideElement.java:67)
	at com.codeborne.selenide.impl.WaitingSelenideElement.invoke(WaitingSelenideElement.java:18)
```
I think that Selenide can be more "smart" and remember the stringified DOM element each time *before* checking the condition, so that when condition fails the error message is not contradictory.

**Comment by asolntsev** [comment]
@dmak Yes, it could. I created a separate feature request for this: https://github.com/codeborne/selenide/issues/217
