### ISSUE TITLE
IllegalArgumentException while using SelenideElement as classic page-object model

### ISSUE THREAD

**Issue by anilreddy** [codeborne/selenide#188]
Hi,

I am using selenideelement as classic page-object model am getting the following error:

```java
@FindBy(id = "searchInputBox")
private SelenideElement myMpSearch;

@FindBy(xpath = "//span[text()='Go']")
private SelenideElement goBtn;

@FindBy(xpath = "//span[contains(.,'Menu') and @class='ng-scope']")
private SelenideElement menu;

and using above page-objects as

sidePanelPageObjects = PageFactory.initElements(driver, SidePanelPageObjects.class);

public void clickOnLink(String linkName) {
		$(byText("Loading")).should(disappear);
		myMpSearch.should(appear).setValue(linkName);
		goBtn.click();
}

```

```java

java.lang.IllegalArgumentException: Can not set com.codeborne.selenide.SelenideElement field com.fpr.ctp.pageobjects.SidePanelPageObjects.myMpSearch to com.sun.proxy.$Proxy10
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(Unknown Source)
	at java.lang.reflect.Field.set(Unknown Source)
	at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:116)
	at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:104)
	at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:91)
	at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:78)
	at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:64)
	at com.uprr.btp.testcases.AddGenericMessageTest.setUp(AddGenericMessageTest.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatchman$1.evaluate(TestWatchman.java:53)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

```
let me know if you need more info.

Thanks,
Anil

**Comment by asolntsev** [comment]
I see that you are using classic `org.openqa.selenium.support.PageFactory`. Naturally, it cannot handle `SelenideElement`s. You just don't need to call `PageFactory.initElements()` in your `AddGenericMessageTest.setUp()`.

You can find a working example of PageObject on selenide site: http://selenide.org/documentation/page-objects.html

As you see, it's even simpler. You don't need any factories. Just create page:
```java
GoogleSearchPage searchPage = open("/login", GoogleSearchPage.class);
```

**Comment by anilreddy** [comment]
OK I got you but. What about if i have multiple page object classes like this do I need to use open for all ?

```java
LoginPage loginPage = open("/login", LoginPage.class); // continuation to this page I have two more
SidePanelPage sidePage = open("", SidePanelPage.class);
AddMessagesPage  addMessagePage = open("", AddMessagesPage.class);
```

**Comment by asolntsev** [comment]
Not necessary. Method open() opens a url in browser. If you want just to initialize page object, just use method page(YourPage.class)

Sent from my HTC

----- Reply message -----
