### ISSUE TITLE
Implement SoftAssert mechanism for JUnit and TestNG

### ISSUE THREAD

**Issue by asolntsev** [codeborne/selenide#19]
For a test marked with @SoftAssert anntation:
If a test contains multiple asserts, it should check them all, and fail only after all checks.

**Comment by LizaLeo** [comment]
I would like to have this feature too. 
I like to use Page object and when I verify how page looks like it nice not to get one exception on the first failed expected element in DOM, but all of them.

**Comment by asolntsev** [comment]
@LizaLeo Finally, I tried to implement soft assertions. Do you like the output like that? Do you really find it useful?

```java
Report for userCanUseSoftAssertWithJUnit(integration.SoftAssertJUnitTest)
+--------------------+----------------------------------------------------------------------+----------+----------+
|Element             |Subject                                                               |Status    |ms.       |
+--------------------+----------------------------------------------------------------------+----------+----------+
|open                |http://0.0.0.0:40777/page_with_selects_without_jquery.html            |PASSED    |5326      |
|#radioButtons input |should have(attribute value=777)                                      |FAILED    |815       |
|#radioButtons select|click()                                                               |FAILED    |941       |
|#xxx                |should be(visible)                                                    |FAILED    |312       |
+--------------------+----------------------------------------------------------------------+----------+----------+


java.lang.AssertionError: Test userCanUseSoftAssertWithJUnit(integration.SoftAssertJUnitTest) failed.
3 checks failed

FAIL #1: Element should have attribute value=777 {#radioButtons input}
Element: '<input name="me" type="radio" value="master"></input>'
Screenshot: file:/Users/andrei/projects/selenide/build/reports/tests/integration/SoftAssertJUnitTest/userCanUseSoftAssertWithJUnit/1425503251321.0.png
Timeout: 0 ms.

FAIL #2: Element not found {#radioButtons select}
Expected: visible
Screenshot: file:/Users/andrei/projects/selenide/build/reports/tests/integration/SoftAssertJUnitTest/userCanUseSoftAssertWithJUnit/1425503252361.1.png
Timeout: 0 ms.
Caused by: NoSuchElementException: Unable to locate element: {"method":"css selector","selector":"#radioButtons select"}

FAIL #3: Element not found {#xxx}
Expected: visible
Screenshot: file:/Users/andrei/projects/selenide/build/reports/tests/integration/SoftAssertJUnitTest/userCanUseSoftAssertWithJUnit/1425503252697.2.png
Timeout: 0 ms.
Caused by: NoSuchElementException: Unable to locate element: {"method":"css selector","selector":"#xxx"}

	at org.junit.Assert.fail(Assert.java:88)
	at com.codeborne.selenide.junit.SoftAsserts.after(SoftAsserts.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:50)
        ....
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
```

**Comment by LizaLeo** [comment]
Great!
Why do you think it's ugly?
If you don't like table output you can output fails without it, just row by row, or what did you mean? 
It looks nice enough for me. At least seems readable. I think it will be also informative enough without table too :) 
The main thing is to implement feature, later it can be improved by someone request if needed.
Thank you!

**Comment by asolntsev** [comment]
@LizaLeo We have released Selenide 2.17 with soft assert for [JUnit](https://github.com/codeborne/selenide/blob/master/src/test/java/integration/SoftAssertJUnitTest.java) and [TestNG](https://github.com/codeborne/selenide/blob/master/src/test/java/integration/testng/SoftAssertTestNGTest.java). Please try it. Waiting for your feedback...

**Comment by asolntsev** [comment]
At the moment, closing the issue. Please reopen if you find it unusable.

**Comment by jeep-guy** [comment]
@asolntsev I am getting the following error when trying to use SoftAsserts for TestNG:

java.lang.NoClassDefFoundError: org/junit/Assert
	at com.codeborne.selenide.logevents.ErrorsCollector.failIfErrors(ErrorsCollector.java:25)
	at com.codeborne.selenide.testng.SoftAsserts.failIfErrors(SoftAsserts.java:43)
	at com.codeborne.selenide.testng.SoftAsserts.onTestFailure(SoftAsserts.java:21)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1833)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1817)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1244)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

I'm not sure if this is relevant to the issue, but my file is a Groovy file, not a Java file.  I have added @Listeners(SoftAsserts) to the top of my file, and I am setting Configuration.assertionMode = Configuration.AssertionMode.SOFT before any of the test logic is executed. I am not sure if this is an error on my part, or if it is a bug with SoftAsserts for TestNG with Selenide. What is your opinion?

**Comment by asolntsev** [comment]
Hi!
it is a bug with SoftAsserts for TestNG with Selenide. I need to fix it.

**Comment by jeep-guy** [comment]
Great. Please let me know when it is fixed. I love Selenide BTW. Thank you so much for creating it! It is truly great, and you have made my life much easier with it!

**Comment by asolntsev** [comment]
Thank you!
I have created an issue on github:
https://github.com/codeborne/selenide/issues/236

Andrei Solntsev

2015-10-22 22:25 GMT+03:00 jeep-guy <notifications@github.com>:
