### ISSUE TITLE
SelenideElement.shouldBe("mesage",condition.exist) throwable message

### ISSUE THREAD

**Issue by admizh** [codeborne/selenide#198]
```java
@Test
    public void google() {
        open("http://ya.ru");
        $("#text").val("yandex");
        $("#notexist").exists(); //return false;
        $("#notexist").shouldBe("Element not found on page",Condition.exist);
}
```
Exception mesage should be: 
Expected: Element not found on page, should be exist
```
Element not found {#notexist}
Expected: exist
Screenshot: file:/C:/Users/I301235/PRO/hackaton/testogram/./screanShots/tests/everify/BugSelenide/google/1437644350077.0.png
Timeout: 4 s.
Caused by: NoSuchElementException: no such element
	at com.codeborne.selenide.impl.AbstractSelenideElement.createElementNotFoundError(AbstractSelenideElement.java:648)
	at com.codeborne.selenide.impl.WaitingSelenideElement.createElementNotFoundError(WaitingSelenideElement.java:74)
	at com.codeborne.selenide.impl.AbstractSelenideElement.checkCondition(AbstractSelenideElement.java:491)
	at com.codeborne.selenide.impl.AbstractSelenideElement.should(AbstractSelenideElement.java:462)
	at com.codeborne.selenide.impl.AbstractSelenideElement.invokeShould(AbstractSelenideElement.java:294)
	at com.codeborne.selenide.impl.AbstractSelenideElement.dispatchSelenideMethod(AbstractSelenideElement.java:180)
	at com.codeborne.selenide.impl.AbstractSelenideElement.dispatchAndRetry(AbstractSelenideElement.java:90)
	at com.codeborne.selenide.impl.AbstractSelenideElement.invoke(AbstractSelenideElement.java:65)
	at com.codeborne.selenide.impl.WaitingSelenideElement.invoke(WaitingSelenideElement.java:18)
	at com.sun.proxy.$Proxy11.shouldBe(Unknown Source)
```

**Comment by asolntsev** [comment]
Hi!
Method shouldBe(string, condition...) is deprecated and will be removed in Selenide 3.0

Please use method shouldBe(condition.because(string)).

Sent from my HTC

----- Reply message -----

**Comment by admizh** [comment]
Soory, Thanks Andrey!
