### ISSUE TITLE
Search element in collection fails with IndexOutOfBoundsException

### ISSUE THREAD

**Issue by cbxp** [codeborne/selenide#205]
Such a check:

```java
$$(".alert-success").findBy(text(message)).shouldBe(visible);
```

should wait for 4 seconds, but it fails with IndexOutOfBoundsException:

```java
Element not found {.alert-success.filter(text 'created')}
Expected: visible
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at com.codeborne.selenide.impl.CollectionElement.createElementNotFoundError(CollectionElement.java:46)
	at com.codeborne.selenide.impl.AbstractSelenideElement.checkCondition(AbstractSelenideElement.java:504)
	at com.codeborne.selenide.impl.AbstractSelenideElement.should(AbstractSelenideElement.java:475)
	at com.codeborne.selenide.impl.AbstractSelenideElement.invokeShould(AbstractSelenideElement.java:298)
	at com.codeborne.selenide.impl.AbstractSelenideElement.dispatchSelenideMethod(AbstractSelenideElement.java:181)
	at com.codeborne.selenide.impl.AbstractSelenideElement.dispatchAndRetry(AbstractSelenideElement.java:91)
	at com.codeborne.selenide.impl.AbstractSelenideElement.invoke(AbstractSelenideElement.java:66)
	at com.codeborne.selenide.impl.CollectionElement.invoke(CollectionElement.java:13)
	at com.sun.proxy.$Proxy105.shouldBe(Unknown Source)
	at play.test.TwitterBootstrapUITest.assertSuccessMessage(TwitterBootstrapUITest.java:18)
```

**Comment by asolntsev** [comment]
Cannot reproduce
