### ISSUE TITLE
Enable using SoftAsserrs with TestNG

### ISSUE THREAD

**Issue by asolntsev** [codeborne/selenide#236]
by @jeep-guy:

```java
I am getting the following error when trying to use SoftAsserts for TestNG:

java.lang.NoClassDefFoundError: org/junit/Assert
at com.codeborne.selenide.logevents.ErrorsCollector.failIfErrors(ErrorsCollector.java:25)
at com.codeborne.selenide.testng.SoftAsserts.failIfErrors(SoftAsserts.java:43)
at com.codeborne.selenide.testng.SoftAsserts.onTestFailure(SoftAsserts.java:21)
at org.testng.internal.Invoker.runTestListeners(Invoker.java:1833)
at org.testng.internal.Invoker.runTestListeners(Invoker.java:1817)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1244)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:617)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
at org.testng.SuiteRunner.run(SuiteRunner.java:254)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
at org.testng.TestNG.run(TestNG.java:1057)
at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:125)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by asolntsev** [comment]
@jeep-guy uuups. Fixed in Selenide 2.24
