### ISSUE TITLE
Unable to use selenide 2.19 with JDK 6

### ISSUE THREAD

**Issue by ameypotnis** [codeborne/selenide#238]
Looks like java 6 doesn't have constructor with java.lang.AssertionError: method (Ljava/lang/String;Ljava/lang/Throwable;)

so I am getting following exception 

java.lang.NoSuchMethodError: java.lang.AssertionError: method (Ljava/lang/String;Ljava/lang/Throwable;)V not found
	at com.codeborne.selenide.ex.UIAssertionError.(UIAssertionError.java:24)
	at com.codeborne.selenide.ex.UIAssertionError.(UIAssertionError.java:16)
	at com.codeborne.selenide.ex.UIAssertionError.wrap(UIAssertionError.java:63)
	at com.codeborne.selenide.impl.AbstractSelenideElement.invoke(AbstractSelenideElement.java:74)
	at com.codeborne.selenide.impl.WaitingSelenideElement.invoke(WaitingSelenideElement.java:18)
	at com.sun.proxy.$Proxy21.shouldBe(Unknown Source)

**Comment by asolntsev** [comment]
Yes, you cannot use java 6 anymore.
The reason is that newest selenium 2.47+ uses java 7.
It's time to upgrade!

By the way, end of java 7 life also becomes soon. I highly recommend using
java 8.

**Comment by ameypotnis** [comment]
@asolntsev : thanks for quick response, I'll try to upgrade my legacy application to Java 8 ;)
