### ISSUE TITLE
selenide does not close the browser

### ISSUE THREAD

**Issue by gitnoor** [codeborne/selenide#240]
following error occurs:
com.codeborne.selenide.impl.WebDriverThreadLocalContainer createDriver
INFO: Create webdriver in current thread 1: firefox -> FirefoxDriver: firefox on WINDOWS (f589d705-2a74-4db5-8694-6dad198c6706)

PM com.codeborne.selenide.impl.WebDriverThreadLocalContainer closeWebDriver
INFO: Close webdriver: 1 -> FirefoxDriver: firefox on WINDOWS (f589d705-2a74-4db5-8694-6dad198c6706)

**Comment by asolntsev** [comment]
@gitnoor I don't see any errors. Both provided logs are INFO messages.

**Comment by gitnoor** [comment]
Exception in thread "Thread-4" java.lang.RuntimeException: Process refused to die after 10 seconds, and couldn't taskkill it: Unable to find executable for: taskkill
	at org.openqa.selenium.os.ProcessUtils.killWinProcess(ProcessUtils.java:142)
	at org.openqa.selenium.os.ProcessUtils.killProcess(ProcessUtils.java:81)
	at org.openqa.selenium.os.UnixProcess$SeleniumWatchDog.destroyHarder(UnixProcess.java:248)
	at org.openqa.selenium.os.UnixProcess$SeleniumWatchDog.access$2(UnixProcess.java:245)
	at org.openqa.selenium.os.UnixProcess.destroy(UnixProcess.java:124)
	at org.openqa.selenium.os.CommandLine.destroy(CommandLine.java:153)
	at org.openqa.selenium.firefox.FirefoxBinary.quit(FirefoxBinary.java:259)
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.quit(NewProfileExtensionConnection.java:202)
	at org.openqa.selenium.firefox.FirefoxDriver$LazyCommandExecutor.quit(FirefoxDriver.java:376)
	at org.openqa.selenium.firefox.FirefoxDriver.stopClient(FirefoxDriver.java:322)
	at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:477)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer$CloseBrowser.run(WebDriverThreadLocalContainer.java:172)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: Unable to find executable for: taskkill
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:250)
	at org.openqa.selenium.os.UnixProcess.<init>(UnixProcess.java:62)
	at org.openqa.selenium.os.CommandLine.<init>(CommandLine.java:38)
	at org.openqa.selenium.os.WindowsUtils.killPID(WindowsUtils.java:172)
	at org.openqa.selenium.os.ProcessUtils.killWinProcess(ProcessUtils.java:138)

**Comment by gitnoor** [comment]
public class GoogleTest {
  @Test
  public void search_selenide_in_google() {
    open("http://google.com/ncr");
    $(By.name("q")).val("selenide").pressEnter();
    $$("#ires .g").shouldHave(size(10));
    $("#ires .g").shouldBe(visible).shouldHave(
        text("Selenide: concise UI tests in Java"),
        text("selenide.org"));
  }
}

in the above example , to identify the webelements such as "ires  .g" will it be highlighted directly by using firebug or do we have to search each division where these elements presents.

**Comment by asolntsev** [comment]
The error message clearly says that you are missing "taskkill" program on
your Windows machine. I guess Selenium needs it to kill Firefox.

**Comment by asolntsev** [comment]
I am not sure I understand your question.
Generally, when you test an application, you should understand how the
application works, including locators
