### ISSUE TITLE
Selenide Field Decorator problems with Lists

### ISSUE THREAD

**Issue by admizh** [codeborne/selenide#245]
Steps to reproduce:
1 - Create page object with one List type field
``` java
public class PageObject {
    private List<? extends Class> PAGES = new ArrayList<>();
}
```
2 - Init this class by method Slenide.page()

Exception has occurred, (Selenide version 2.23)
``` java
at com.codeborne.selenide.Selenide.page(Selenide.java:420)
	...
Caused by: java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.WildcardTypeImpl cannot be cast to java.lang.Class
	at com.codeborne.selenide.impl.SelenideFieldDecorator.getListGenericType(SelenideFieldDecorator.java:98)
	at com.codeborne.selenide.impl.SelenideFieldDecorator.isDecoratableList(SelenideFieldDecorator.java:88)
	at com.codeborne.selenide.impl.SelenideFieldDecorator.decorate(SelenideFieldDecorator.java:42)
	at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:112)
	at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:104)
	at com.codeborne.selenide.Selenide.page(Selenide.java:429)
	at com.codeborne.selenide.Selenide.page(Selenide.java:418)
	... 29 more
```

**Comment by asolntsev** [comment]
@admizh But what is the expected behaviour? What values should be injected into `PAGES`?
It does not have any `@FindBy` annotation, so?...

**Comment by admizh** [comment]
@asolntsev I add to the list is not initialized classes, like this:
```java
PAGES.add(PageObject.class);
```
Also my collection field not anotated with @FindBy(s);
This fix in com.codeborne.selenide.impl.SelenideFieldDecorator#isDecoratableList should be resolve problem:
```java
  private boolean isDecoratableList(Field field, Class<?> type) {
    if (!List.class.isAssignableFrom(field.getType())) {
      return false;
    }
    if (field.getAnnotation(FindBy.class) == null || field.getAnnotation(FindBys.class) == null) {
      return false;
    }
    Class<?> listType = getListGenericType(field);
    return listType != null && type.isAssignableFrom(listType);
  }
```
