### ISSUE TITLE
Screenshot is not created for ElementNotFound exception

### ISSUE THREAD

**Issue by dmak** [codeborne/selenide#292]
In the example below the screenshot should be created but it is not:

```
test_176(org.mycompany.Test)  Time elapsed: 60.241 sec  <<< FAILURE!
com.codeborne.selenide.ex.ElementNotFound: Element not found {#tab-area li[aria-controls='08016978']}
Expected: css class 'done'
	at sun.reflect.GeneratedConstructorAccessor9.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:595)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:348)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByCssSelector(RemoteWebDriver.java:437)
	at org.openqa.selenium.By$ByCssSelector.findElement(By.java:426)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:340)
	at com.codeborne.selenide.impl.WebElementSelector.findElement(WebElementSelector.java:28)
	at com.codeborne.selenide.impl.WaitingSelenideElement.getActualDelegate(WaitingSelenideElement.java:56)
	at com.codeborne.selenide.impl.AbstractSelenideElement.checkCondition(AbstractSelenideElement.java:528)
	at com.codeborne.selenide.impl.AbstractSelenideElement.should(AbstractSelenideElement.java:517)
	at com.codeborne.selenide.impl.AbstractSelenideElement.invokeShould(AbstractSelenideElement.java:305)
	at com.codeborne.selenide.impl.AbstractSelenideElement.dispatchSelenideMethod(AbstractSelenideElement.java:179)
	at com.codeborne.selenide.impl.AbstractSelenideElement.dispatchAndRetry(AbstractSelenideElement.java:90)
	at com.codeborne.selenide.impl.AbstractSelenideElement.invoke(AbstractSelenideElement.java:65)
	at com.codeborne.selenide.impl.WaitingSelenideElement.invoke(WaitingSelenideElement.java:19)
	at com.sun.proxy.$Proxy7.waitUntil(Unknown Source)
	at org.mycompany.CommonUtils.waitForPanelToLoad(CommonUtils.java:171)
Caused by: org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"css selector","selector":"#tab-area li[aria-controls='08016978']"}
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.47.1', revision: 'unknown', time: '2015-07-30 11:02:44'
System info: host: 'luu128d', ip: '10.14.1.85', os.name: 'Linux', os.arch: 'amd64', os.version: '3.0.101-63-default', java.version: '1.7.0_25'
Driver info: driver.version: unknown
	at <anonymous class>.FirefoxDriver.prototype.findElementInternal_(file:///tmp/anonymous8049683132435027632webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:10667)
	at <anonymous class>.FirefoxDriver.prototype.findElement(file:///tmp/anonymous8049683132435027632webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:10676)
	at <anonymous class>.DelayedCommand.prototype.executeInternal_/h(file:///tmp/anonymous8049683132435027632webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12643)
	at <anonymous class>.DelayedCommand.prototype.executeInternal_(file:///tmp/anonymous8049683132435027632webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12648)
	at <anonymous class>.DelayedCommand.prototype.execute/<(file:///tmp/anonymous8049683132435027632webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12590)
```

**Comment by asolntsev** [comment]
With help of Máté Kiss I could reproduce the problem.

In test report generated by Jenkins: https://ci.selenide.org/job/selenide-maven-testng/20/testReport/com.reindeermobile.selenide/GoogleTest/failedTest/

There is no screenshot path in error message.

Though, if we look into surefire report, there is screenshot path:
https://ci.selenide.org/job/selenide-maven-testng/20/artifact/target/surefire-reports/index.html

It seems to be a strange behaviour of TestNG or Maven or Jenkins.
I need to investigate it.

**Comment by dmak** [comment]
In my scenario we are using JUnit and Jenkins v1.580 (freestyle job).

**Comment by asolntsev** [comment]
@dmak Can you provide a test and exact instructions how I could reproduce the problem?

**Comment by dmak** [comment]
I am monitoring the behaviour of Selenide v3.7 and so far it works correctly. I will keep on watching for a couple of weeks, but preliminary it works fine.
