### ISSUE TITLE
Java selenide script fails when running .jar on Linux server InvocationTargetException

### ISSUE THREAD

**Issue by m-alkaswan** [codeborne/selenide#294]
I have a Selenide script that is doing some automation work for me. I connect to a Selenium grid and use the chrome browser there to do all of the actions in the script. When I execute the script on Eclipse, it works fine. When I export the script as a runnable jar, I am able to run it through the Windows command line using

`java -jar myJar.jar`
command.

But once I upload it to a jenkins server with Solaris Linux it fails every time. I get the following error:

`[oracle@***** tmp]$ ./Pega7GetRuleSet.jar chrome
Java Accessibility Bridge for GNOME loaded.

Feb 15, 2016 4:09:53 PM     com.codeborne.selenide.impl.WebDriverThreadLocalContaine                                                                                        r maximize
WARNING: Cannot maximize chrome: java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
Feb 15, 2016 4:09:53 PM com.codeborne.selenide.impl.WebDriverThreadLocalContaine                                                                                        r createDriver
INFO: Create webdriver in current thread 1: chrome -> RemoteWebDriver: chrome on                                                                                              XP
######################## LOGIN ########################
Entered username
Entered password
Clicking on login button
######################## Get Rules ########################
Clicking on records
Exception in thread "main" java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.                                                                                        java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces                                                                                        sorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoa                                                                                        der.java:58)
Caused by: java.lang.NoSuchMethodError: java.lang.AssertionError: method <init>(                                                                                        Ljava/lang/String;Ljava/lang/Throwable;)V not found
    at com.codeborne.selenide.ex.UIAssertionError.<init>(UIAssertionError.ja                                                                                        va:24)
    at com.codeborne.selenide.ex.UIAssertionError.<init>(UIAssertionError.ja                                                                                        va:16)
    at com.codeborne.selenide.ex.UIAssertionError.wrap(UIAssertionError.java                                                                                        :63)
    at com.codeborne.selenide.impl.AbstractSelenideElement.invoke(AbstractSe                                                                                        lenideElement.java:75)
    at com.codeborne.selenide.impl.WaitingSelenideElement.invoke(WaitingSele                                                                                        nideElement.java:18)
    at com.sun.proxy.$Proxy1.click(Unknown Source)
    at automationFramework.PegaGetRulesets.main(PegaGetRulesets.java:54)
    ... 5 more`

This is line 54:
`$(By.xpath("/html/body/div[3]/div[3]/div[1]/div/div/table/tbody/tr/td[1]/ul/li[5]/a")).click();`

I have a Selenide script that is doing some automation work for me. I connect to a Selenium grid and use the chrome browser there to do all of the actions in the script. When I execute the script on Eclipse, it works fine. When I export the script as a runnable jar, I am able to run it through the Windows command line using

java -jar myJar.jar 
command.

But once I upload it to a jenkins server with Solaris Linux it fails every time. I get the following error:

[oracle@***** tmp]$ ./Pega7GetRuleSet.jar chrome
Java Accessibility Bridge for GNOME loaded.

Feb 15, 2016 4:09:53 PM     com.codeborne.selenide.impl.WebDriverThreadLocalContaine                                                                                        r maximize
WARNING: Cannot maximize chrome: java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
Feb 15, 2016 4:09:53 PM com.codeborne.selenide.impl.WebDriverThreadLocalContaine                                                                                        r createDriver
INFO: Create webdriver in current thread 1: chrome -> RemoteWebDriver: chrome on                                                                                              XP
######################## LOGIN ########################
Entered username
Entered password
Clicking on login button
######################## Get Rules ########################
Clicking on records
Exception in thread "main" java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.                                                                                        java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces                                                                                        sorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoa                                                                                        der.java:58)
Caused by: java.lang.NoSuchMethodError: java.lang.AssertionError: method <init>(                                                                                        Ljava/lang/String;Ljava/lang/Throwable;)V not found
    at com.codeborne.selenide.ex.UIAssertionError.<init>(UIAssertionError.ja                                                                                        va:24)
    at com.codeborne.selenide.ex.UIAssertionError.<init>(UIAssertionError.ja                                                                                        va:16)
    at com.codeborne.selenide.ex.UIAssertionError.wrap(UIAssertionError.java                                                                                        :63)
    at com.codeborne.selenide.impl.AbstractSelenideElement.invoke(AbstractSe                                                                                        lenideElement.java:75)
    at com.codeborne.selenide.impl.WaitingSelenideElement.invoke(WaitingSele                                                                                        nideElement.java:18)
    at com.sun.proxy.$Proxy1.click(Unknown Source)
    at automationFramework.PegaGetRulesets.main(PegaGetRulesets.java:54)
    ... 5 more
And to show you line 54 of my script:

$(By.xpath("/html/body/div[3]/div[3]/div[1]/div/div/table/tbody/tr/td[1]/ul/li[5]/a")).click();
I export the jar using Eclipse (right click on project, export as runnable jar). I am using Java 1.6 on both the development machine and the server. As you can see the script starts executing some of the login steps, but fails at a later step finding an element.

**Comment by vinogradoff** [comment]
It doesn't look for me that your question is Selenide relevant.

I am not aware what is the technology behind "exporting in Eclipse as executable jar".

We suggest using maven or gradle as a test runner, if you had then problems, we could probably help.

**Comment by vinogradoff** [comment]
Also, Java 7 is required for Selenium (which is what Selenide uses), so probably you must upgrade it too.

**Comment by asolntsev** [comment]
Agree. The problem happens because you compile and run tests with different Selenide versions. Closing the issue.

**Comment by m-alkaswan** [comment]
@asolntsev @vinogradoff 

Not sure what you mean with different Selenide versions. I am running and compiling this on my local machine with Java 1.6. The Linux machine where I execute it also has Java 1.6. The Selenide version I'm using is 2.20 and not the latest.
