### ISSUE TITLE
ConcurrentModificationException in SimpleReport

### ISSUE THREAD

**Issue by ken-p** [codeborne/selenide#303]
`java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at java.util.Collections$UnmodifiableCollection$1.next(Unknown Source)
	at com.codeborne.selenide.logevents.SimpleReport.finish(SimpleReport.java:32)
	at com.codeborne.selenide.testng.TextReport.onTestSuccess(TextReport.java:31)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1695)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1675)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:700)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)`

Sorry I don't have a reproducible test case, but I can see about working on one if the problem isn't obvious to you.  Thanks!

**Comment by asolntsev** [comment]
Wow, cool!
Thank you for reporting, I will investigate it.

**Comment by djangofan** [comment]
@ken-p   Are you forking threads by 'methods' or by 'classes' ?

**Comment by ken-p** [comment]
@djangofan yes, by method.

**Comment by asolntsev** [comment]
@ken-p it's kind of concurrency issue. Two threads are changing the same list at the same time.
But I cannot see how is it possible.
Please do your best to provide a working example, so that I could reproduce the issue.

**Comment by ken-p** [comment]
I haven't seen it since! I'll try to reproduce. Thanks.

**Comment by asolntsev** [comment]
@ken-p I got it! The problem may happen when you run tests in parallel by TestNG. 
See issue #364

**Comment by djangofan** [comment]
JUnit5 has removed the `@Rule` notation. I wonder how that might affect this?

**Comment by asolntsev** [comment]
@djangofan I havn't researched JUnit5 yet. I guess they will provide some migration guide.

**Comment by asolntsev** [comment]
@ken-p It should be fixed now. Will release version 3.8 soon.

**Comment by ken-p** [comment]
Thanks!!
