### ISSUE TITLE
Downloading a file in Jenkins does not work

### ISSUE THREAD

**Issue by thasherwin** [codeborne/selenide#317]
Downloading a file in Jenkins does not work. This does work when running the same test on my windows machine

When i try to download a file in jenkins i get the following error:

NoClassDefFoundError: org/apache/http/ssl/TrustStrategy

Code used
```java
try {
			File downloadedFile = $(".btn.btn-default").download();
			assertThat("Check if file: mailmerge.xls is downloaded","mailmerge.xls", org.hamcrest.Matchers.equalTo(downloadedFile.getName()));

		} catch (FileNotFoundException e) {
			e.printStackTrace();
		}

```

Statck trace:
Caused by: java.lang.NoClassDefFoundError: org/apache/http/ssl/TrustStrategy
	at com.codeborne.selenide.ex.UIAssertionError.wrapThrowable(UIAssertionError.java:63)
	at com.codeborne.selenide.ex.UIAssertionError.wrap(UIAssertionError.java:59)
	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:67)
	at com.sun.proxy.$Proxy17.download(Unknown Source)
	at GXScripts.Other.SmallStories.DownloadFile.FileDownloadVerify.testIfFileCanBeDownloaded(FileDownloadVerify.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:197)
	at main.BaseTest.run(BaseTest.java:275)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:209)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: org/apache/http/ssl/TrustStrategy
	at com.codeborne.selenide.commands.DownloadFile.execute(DownloadFile.java:14)
	at com.codeborne.selenide.commands.DownloadFile.execute(DownloadFile.java:11)
	at com.codeborne.selenide.commands.Commands.execute(Commands.java:136)
	at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:82)
	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:58)
	... 25 more
Caused by: java.lang.ClassNotFoundException: org.apache.http.ssl.TrustStrategy
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 30 more

**Comment by asolntsev** [comment]
This is clearly a problem with conflicting dependencies in your project.
You need to review your `pom.xml` or `build.gradle` and find out which version of `org.apache.httpcomponents:httpcore` dependency is used in your project.

**Comment by thasherwin** [comment]
I also thought it was related to `org.apache.httpcomponents:httpcore` and i removed this dependency. Still it is failing. I am using a `pom.xml`. Do i need to use a speceific version?

btw. The jenkins machine is running on linux.

**Comment by thasherwin** [comment]
NoClassDefFoundError: org/apache/http/ssl/TrustStrategy issue was solved by adding the following dependencies:
```
<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpcore</artifactId>
			<version>4.4</version>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<version>4.5.2</version>
		</dependency>
```
But now it is still failing in Jenkins with another error related to proxy; com.sun.proxy.$Proxy14.download:

```
UndeclaredThrowableException: null
java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy14.download(Unknown Source)
	at GXScripts.Other.SmallStories.DownloadFile.FileDownloadVerify.testIfFileCanBeDownloaded(FileDownloadVerify.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:197)
	at main.BaseTest.run(BaseTest.java:228)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:209)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Network is unreachable
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:337)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at com.codeborne.selenide.impl.FileDownloader.executeHttpRequest(FileDownloader.java:78)
	at com.codeborne.selenide.impl.FileDownloader.download(FileDownloader.java:56)
	at com.codeborne.selenide.commands.DownloadFile.execute(DownloadFile.java:14)
	at com.codeborne.selenide.commands.DownloadFile.execute(DownloadFile.java:11)
	at com.codeborne.selenide.commands.Commands.execute(Commands.java:136)
	at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:82)
	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:58)
	... 25 more
```

**Comment by asolntsev** [comment]
@thasherwin I see `Caused by: java.net.SocketException: Network is unreachable`
It seems to be a network issue. I guess test cannot connect to the server to download file from.

Or.. hm... do you use proxy server in webdriver?

**Comment by thasherwin** [comment]
@asolntsev 

I don't use proxy server in webdriver. Tests do run on a browser that has proxy configured to get access to the acceptance environment.

**Comment by asolntsev** [comment]
@thasherwin Well, in this case you should not have such a problem.

Anyway, in next version of Selenide we are going to rework the download mechanism, so that it will work through a selenide proxy server. It should solve your problem.

**Comment by thasherwin** [comment]
@asolntsev
Sounds nice. I was already waiting for the next version to be released because there are some interesting functionalities  added

**Comment by asolntsev** [comment]
@thasherwin Have you tried Selenide 3.9.1? 
It now downloads files using embedded proxy server. Does it solve your problem?

**Comment by thasherwin** [comment]
It is solved. Not getting the error anymore. I will close it. I do have another problem with the company jenkins server related to proxy that I need to look into to confirm that download is 100% working.
