### ISSUE TITLE
Conditional wait vs implicitlyWait

### ISSUE THREAD

**Issue by hana9090** [codeborne/selenide#322]
Guys, please help me in understanding the following issue. please.

I have to get all links and check them later. I used the following code:

    open(url);
    List<String> links = new ArrayList<>();
    for (SelenideElement link : $$("a"))
        links.add(link.attr("href"));

when I used this with Linux with these api version:
    Maven 3.1
    Selenide v3.5
    Selenium v2.53
    Firefox v45.0.1
Then code can't take time enough to catch links from the page. Then I have to add driver wait before get links.
I Add the following (which is conditional wait):

    WebDriverWait waitLog = new WebDriverWait(WebDriverRunner.getWebDriver(), 20);
    waitLog.until(ExpectedConditions.visibilityOf($(By.tagName(Selector))));

**And it worked fine and I run it more than one time.**

> I got surprised when running it yesterday, it didn't work and can't get time enough to get links!

So I replace the conditional wait with implicit wait, and add the following:

    WebDriverRunner.getWebDriver().manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);	

Now it is working fine.

- What happened? 

- What is this thing make it work sometimes and sometimes can't work?

- How to return back to the conditional wait with keeping the code working well?

So how to recover this problem? and prevent this problem from happens in the future.

**Comment by thasherwin** [comment]
Sounds like you are facing the same problem I had.

https://github.com/codeborne/selenide/issues/283

**Comment by asolntsev** [comment]
@hana9090 Selenide 3.5 does not wait until the page is completely loaded. You should wait until the collection is loaded: $$("a").shouldHave(size(8)).

Then you can iterate collection elements.

**Comment by hana9090** [comment]
@asolntsev, Please, size(8) represent for what?

**Comment by hana9090** [comment]
@asolntsev 
I have this error!!
> expected: = 8, actual: 311, collection: a
I don't need an expectation for the number of a href links.
I need thing make a conditional wait without limitation for the number of [a].

**Comment by thasherwin** [comment]
@hana9090
you are using the should have method to make sure that the links are loaded to proceed with your other test. I guess you can use shouldHave(sizeGreaterThan(300)). Once that function is executed I guess that all collection are loaded. If this function is failing you might need 3.5.1 version of Selenide

**Comment by asolntsev** [comment]
@thasherwin thank you for the answer!

@hana9090 That's right, you can use `$$("a").shouldHave(sizeGreaterThan(300));`

**Comment by thasherwin** [comment]
@asolntsev

No problem!

**Comment by hana9090** [comment]
Thank you @thasherwin  and @asolntsev  :)

**Comment by thasherwin** [comment]
np @hana9090

**Comment by hana9090** [comment]
@asolntsev @thasherwin 
Please I have one more question.
why if there is a delay in opening url then it will give a error: list mismatch of the expected elements.

I think it should wait for loading the page, is it right?

**Comment by thasherwin** [comment]
@hana9090 
Can you please share the complete error log?

**Comment by hana9090** [comment]
For this code:
```
open(Common.url);
$$("a").shouldHave(sizeGreaterThan(1));
```

this error:

>ListSizeMismatch : expected: > 1, actual: 0, collection: a
Elements: []
Screenshot: 
Timeout: 6 s.
	at com.codeborne.selenide.collections.SizeGreaterThan.fail(SizeGreaterThan.java:24)
	at com.codeborne.selenide.ElementsCollection.waitUntil(ElementsCollection.java:106)
	at com.codeborne.selenide.ElementsCollection.should(ElementsCollection.java:56)
	at com.codeborne.selenide.ElementsCollection.shouldHave(ElementsCollection.java:49)
	at Test_Product_Order_Categories.TestProductOrderCategories(Test_Product_Order_Categories.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by thasherwin** [comment]
Do you use Selenide version 3.5.1?

**Comment by hana9090** [comment]
Yes, Selenide version 3.5.1

**Comment by thasherwin** [comment]
Could it be that page strategy is set to eager and you should change it to normal by doing this? `Configuration.pageLoadStrategy="normal"; `
I am not sure whether this will solve your issue.

**Comment by asolntsev** [comment]
@hana9090 @thasherwin It's not a timing issue. Page loading strategy would not help.
You actually **do not have** these elements on your page.

Look, this log clearly says that Selenide tried to wait for these elements for 6 seconds - and still didn't find them:

```
ListSizeMismatch : expected: > 1, actual: 0, collection: a
Elements: []
Screenshot: 
Timeout: 6 s.
```

**Comment by hana9090** [comment]
@asolntsev @thasherwin 
Please, Then how to overcome this problem?

**Comment by thasherwin** [comment]
@hanna9090
Please check if element; a exist on your page.  Maybe you made a typo. If it really exist, please increase the collectionsTimeout by doing for example: Configuration.collectionsTimeout = 15000. He will now try to retrieve the collection with a timeout of 15 seconds
