### ISSUE TITLE
problem with Remote

### ISSUE THREAD

**Issue by Co6aka364** [codeborne/selenide#332]
When connect to selenium grid catch exception:
(selenium-server-standalone-2.53)

java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map

	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:251)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:158)
	at com.codeborne.selenide.webdriver.WebDriverFactory.createRemoteDriver(WebDriverFactory.java:63)
	at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:38)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.createDriver(WebDriverThreadLocalContainer.java:214)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.getAndCheckWebDriver(WebDriverThreadLocalContainer.java:114)
	at com.codeborne.selenide.WebDriverRunner.getAndCheckWebDriver(WebDriverRunner.java:118)
	at com.codeborne.selenide.impl.Navigator.navigateToAbsoluteUrl(Navigator.java:44)
	at com.codeborne.selenide.impl.Navigator.open(Navigator.java:25)
	at com.codeborne.selenide.Selenide.open(Selenide.java:51)

**Comment by imtiazhossain** [comment]
I'm having the same issue with Selenium 2.53.0 with selenide 3.5.1.

java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:251)
  at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
  at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:158)
  at com.codeborne.selenide.webdriver.WebDriverFactory.createRemoteDriver(WebDriverFactory.java:63)
  at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:38)
  at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.createDriver(WebDriverThreadLocalContainer.java:214)
  at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.getAndCheckWebDriver(WebDriverThreadLocalContainer.java:114)
  at com.codeborne.selenide.WebDriverRunner.getAndCheckWebDriver(WebDriverRunner.java:118)
  at com.codeborne.selenide.impl.Navigator.navigateToAbsoluteUrl(Navigator.java:44)
  at com.codeborne.selenide.impl.Navigator.open(Navigator.java:23)
  at com.codeborne.selenide.Selenide.open(Selenide.java:51)
  at stepDefinitions.StepDefinitions.navigateToYouVisit(StepDefinitions.java:26)

**Comment by asolntsev** [comment]
@Co6aka364 @imtiazhossain
I found a similar issue in Selenium: https://groups.google.com/forum/#!msg/selenium-users/hQfiR5u147A/GWfvca7bAtUJ

It seems that you are using an old Grid 1.x

> RemoteWebDriver is Selenium2 API and it CANNOT work with Selenium-Grid-1.0.8

**Comment by imtiazhossain** [comment]
I'm using grid 2.53.0

![image](https://cloud.githubusercontent.com/assets/7926510/15251297/b8230852-18f6-11e6-9edd-b5af482005c8.png)

**Comment by asolntsev** [comment]
@Co6aka364 @imtiazhossain 
Yuhuu!
I have found the cause of this problem.
You need to use remote url `http://localhost:4444/wd/hub`, not `http://localhost:4444/grid` or something else.
