### ISSUE TITLE
Selenide doesn't work for notify element

### ISSUE THREAD

**Issue by Rajahuli** [codeborne/selenide#336]
i tried to automate a page on this notification comes as acknowledgement after doing some actions notification stays on screen for few seconds later disappears.
But selenide did not identify this element.
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

Element not found {By.xpath: //div[@class='ui-pnotify ']//div[@class='ui-pnotify-text']}
Expected: visible

Screenshot: file:/Users/venkatesh.ainalli/Applications/Workspace/Regression3.5/build/reports/tests/1463163608768.0.png
Timeout: 4 s.
Caused by: NoSuchElementException: Unable to locate element: {"method":"xpath","selector":"//div[@class='ui-pnotify ']//div[@class='ui-pnotify-text']"}
	at com.codeborne.selenide.impl.WebElementSource.createElementNotFoundError(WebElementSource.java:31)
	at com.codeborne.selenide.impl.ElementFinder.createElementNotFoundError(ElementFinder.java:82)
	at com.codeborne.selenide.impl.WebElementSource.checkCondition(WebElementSource.java:59)
	at com.codeborne.selenide.commands.Should.should(Should.java:35)
	at com.codeborne.selenide.commands.Should.execute(Should.java:29)
	at com.codeborne.selenide.commands.Should.execute(Should.java:12)
	at com.codeborne.selenide.commands.Commands.execute(Commands.java:136)
	at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:82)
	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:58)
	at com.sun.proxy.$Proxy5.should(Unknown Source)
	at com.tests.appcenter.modules.Groups.GroupsPage.createUserGroup(GroupsPage.java:34)
	at com.tests.appcenter.modules.Groups.runGroupTests.navigateToGroups(runGroupTests.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"xpath","selector":"//div[@class='ui-pnotify ']//div[@class='ui-pnotify-text']"}
Command duration or timeout: 12 milliseconds

**Comment by asolntsev** [comment]
I believe it's not a Selenide bug. This element does not exist on this page. Selenide has been waiting for 4 seconds, but still could not find it. You probably used the wrong xpath.

By the way, instead of complex xpath: //div[@class='ui-pnotify ']//div[@class='ui-pnotify-text'] you can use much simpler css selector: 

$(".ui-pnotify .ui-pnotify-text")

**Comment by Rajahuli** [comment]
Yup got it thanks!!! it was my mistake sorry xpath was wrong
