### ISSUE TITLE
UnreachableBrowserException on simple test

### ISSUE THREAD

**Issue by fortiernor** [codeborne/selenide#350]
I am trying Selenide with the simple
    open("http://www.google.ca");
But I get an error (see output below; unfortunately gradle truncated it).
Any suggestion as to how to correct? I notice you do not provide any explanation on how to configure webdrivers, if I am missing something really basic please suggest further reading.
Thank you!

    org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
    Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
    System info: host: '[...]', ip: '[...]', os.name: 'Linux', os.arch: 'amd64', os.version: '4.6.2-1-ARCH', java.version: '1.8.0_92'
    Driver info: driver.version: FirefoxDriver
    selenide.url: http://www.google.ca
    selenide.baseUrl: http://localhost:8080
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:665)
    at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
    at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:216)
    at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
    at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:128)
    at com.codeborne.selenide.webdriver.WebDriverFactory.createFirefoxDriver(WebDriverFactory.java:110)
    at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:44)
    at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.createDriver(WebDriverThreadLocalContainer.java:214)
    at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.getAndCheckWebDriver(WebDriverThreadLocalContainer.java:114)
    at com.codeborne.selenide.WebDriverRunner.getAndCheckWebDriver(WebDriverRunner.java:126)
    at com.codeborne.selenide.impl.Navigator.navigateToAbsoluteUrl(Navigator.java:70)
    at com.codeborne.selenide.impl.Navigator.open(Navigator.java:33)
    at com.codeborne.selenide.Selenide.open(Selenide.java:79)
    at com.codeborne.selenide.Selenide.open(Selenide.java:53)
    at ca.archives.rdacs.ExploreSelenideTest.userCanLoginByUsername(ExploreSelenideTest.java:41)

**Comment by vinogradoff** [comment]
Selenium 2.53.0 doesn't work with Firefox 47 yet. Downgrade to 46 or wait for Selenium fix. 

Viele Grüße
Alexei Vinogradov 
--
Sent from mobile phone

**Comment by shimkiv** [comment]
Or use MarionetteDriver instead.
https://www.mozilla.org/en-US/firefox/47.0/releasenotes/

**Comment by asolntsev** [comment]
@fortiernor Or try chromedriver. From my experience, it's the most fast and stable webdriver.
