### ISSUE TITLE
   File file = Screenshots.takeScreenShot($("#content_left"));

### ISSUE THREAD

**Issue by joshLV** [codeborne/selenide#373]
File file = Screenshots.takeScreenShot($("#content_left"));

java.awt.image.RasterFormatException: (y + height) is outside of Raster
	at sun.awt.image.ByteInterleavedRaster.createWritableChild(ByteInterleavedRaster.java:1248)
	at java.awt.image.BufferedImage.getSubimage(BufferedImage.java:1203)
	at com.codeborne.selenide.impl.ScreenShotLaboratory.takeScreenshotAsImage(ScreenShotLaboratory.java:128)
	at com.codeborne.selenide.impl.ScreenShotLaboratory.takeScreenshot(ScreenShotLaboratory.java:97)
	at com.codeborne.selenide.Screenshots.takeScreenShot(Screenshots.java:39)
	at org.selenide.examples.GoogleSearchTest.screenshot(GoogleSearchTest.java:57)
	at org.selenide.examples.GoogleSearchTest.tearDown(GoogleSearchTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by asolntsev** [comment]
Hi!
Thanks for reporting the issue.

Could you please give a URL of page you are testing? I need to reproduce
the problem by myself.

**Comment by joshLV** [comment]
open("https://www.baidu.com");
    $(By.id("kw")).val("selenide");

    $(By.id("su")).click();
    $(byText("Loading")).waitUntil(disappears, 300000);
   $("#container").find("div.nums").shouldHave(text("百度为您找到相关结果"));

**Comment by joshLV** [comment]
Point p = element.getLocation();
    Dimension elementSize = element.getSize();
   try {
      BufferedImage img = ImageIO.read(new ByteArrayInputStream(screen));
      BufferedImage dest = img.getSubimage(p.getX(), p.getY(), elementSize.getWidth(), elementSize.getHeight());
      return dest;
    }

p
     x=0
     y=133
elementSize
      height=1345
      width=661
img
    width = 1350 height = 679

**Comment by asolntsev** [comment]
@joshLV Thank you, this information should help. I will try it.

**Comment by BorisOsipov** [comment]
Hi @asolntsev,
Reason of the issue that "#content_left" div has height more than page screenshot. I prepare fix: just cut off screenshot size for WebElement :)

@joshLV If you realy want strong tool to work with WebElements screenshots I suggest you have a look at https://github.com/yandex-qatools/ashot

Thanks,
Boris

**Comment by joshLV** [comment]
Thank you
