### ISSUE TITLE
Selenium,Selenide- java.lang.IndexOutOfBoundsException: Invalid index 3, size is 3

### ISSUE THREAD

**Issue by hana9090** [codeborne/selenide#377]
I am writing a selenium code to clear list of items that defined in a table.
clearing item by clicking delete icon. I am doing the following:

1- Read all items
2- Save them in array list of SelenideElement Array.
3- click on delete icon for each item row, by make a loop on the Arraylist.

Although I am using size limit of items in the Arraylist, there is **IndexOutOfBoundsException** generated!!

Still I don't know why! As code shown, we can't reach the index which exceed the Array size limit.
code is working well, items will be deleted unless the the number items reached 2! So why it was working but when the size getting decreased the code will caused an Exception! 

My code:

```
List<SelenideElement> list_items = new ArrayList<>();
    for (SelenideElement Obj : $("#tableX").$$("tr")) 
        list_items.add(Obj.$$("td").get(4).$("a"));

    for (int t = 0; t < list_items.size();t++) {
        if (t < list_items.size()) {
            ((JavascriptExecutor) WebDriverRunner.getWebDriver()).executeScript("arguments[0].click();", list_items.get(t));
            WebDriverRunner.getWebDriver().manage().timeouts().implicitlyWait(6,
            TimeUnit.SECONDS);
            WebDriverRunner.getWebDriver().navigate().to("https://url/tableItems");
            $$("a").shouldHave(sizeGreaterThan(1));

        }
    }
```

Error Log:

```
java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
    at java.util.ArrayList.rangeCheck(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at com.codeborne.selenide.impl.CollectionElement.getWebElement(CollectionElement.java:29)
    at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:85)
    at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:58)
    at com.sun.proxy.$Proxy9.findElements(Unknown Source)
    at com.codeborne.selenide.impl.WebElementSelector.findElements(WebElementSelector.java:37)
    at com.codeborne.selenide.impl.BySelectorCollection.getActualElements(BySelectorCollection.java:28)
    at com.codeborne.selenide.impl.CollectionElement.getWebElement(CollectionElement.java:29)
    at com.codeborne.selenide.commands.ToWebElement.execute(ToWebElement.java:11)
    at com.codeborne.selenide.commands.ToWebElement.execute(ToWebElement.java:8)
    at com.codeborne.selenide.commands.Commands.execute(Commands.java:136)
    at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:52)
    at com.sun.proxy.$Proxy9.toWebElement(Unknown Source)
    at com.codeborne.selenide.impl.ElementFinder.getSearchContext(ElementFinder.java:69)
    at com.codeborne.selenide.impl.ElementFinder.getWebElement(ElementFinder.java:56)
    at com.codeborne.selenide.commands.GetWrappedElement.execute(GetWrappedElement.java:11)
    at com.codeborne.selenide.commands.GetWrappedElement.execute(GetWrappedElement.java:8)
    at com.codeborne.selenide.commands.Commands.execute(Commands.java:136)
    at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:82)
    at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:58)
    at com.sun.proxy.$Proxy9.getWrappedElement(Unknown Source)
```

Please, Any help?

**Comment by hana9090** [comment]
@asolntsev 
Please, Any help ?

**Comment by asolntsev** [comment]
@hana9090 Ough, what a complex code!
Please, PLEASE, **keep it simple**!

* Why use implicit wait?
* Why put all links to a list?
* Why use `WebDriverRunner.getWebDriver().navigate().to(url)` instead of just `open(url)`? 
* Why use `if (t < list_items.size())` inside loop? This condition is always `true`!

I guess your test should fail because you go left the page inside the loop (you navigate to url `"https://url/tableItems"`). But from the stack trace, I still don't see from what line of your test the exception raises. Please provide full stack trace, and full code of your test.

**Comment by hana9090** [comment]
@asolntsev 
I have changed my code only to delete the items by get the first item in the table and delete it.
and it doing very well without any exception, the table it is successfully deleted.

it worked at Windows environment using maven and also at linux aws it worked,
but when I try to do background process (using crontab job) to call the bash script to execute tests, I have a problem that table is not cleared so the test it didn't work well.


```
count =  $("#tableX").$$("tr");
// always delete the first row until reach count


for (int i = 0; i < count; i++)
{
	((JavascriptExecutor) WebDriverRunner.getWebDriver()).executeScript("arguments[0].click();",
	$("#tableX").$$("tr").get(0).$$("td").get(4).$("a"));
	$$("a").shouldHave(sizeGreaterThan(1));
}
```


What the differences between using` WebDriverRunner.getWebDriver().navigate().to(url)` or `open(url)`?

**Comment by asolntsev** [comment]
@hana9090 There is no difference. 
Your code is equivalent to 

```java
executeScript("arguments[0].click();"
```

Moreover, it's equivalent to

```java
  $("#tableX").$$("tr").get(0).$$("td").get(4).$("a")).click();
```

**Comment by rosolko** [comment]
@hana9090 
Any update related to you issue?
I'm closing it for now but if needed feel free to reopen with additional information.
