### ISSUE TITLE
Selenide swallows exception in some cases

### ISSUE THREAD

**Issue by asolntsev** [codeborne/selenide#401]
For example, if exception is thrown from constructor of class `Commands`, Selenide will swallow it, and report just `ElementShouldBe(visible)` exception (or something similar). 

```java
java.lang.NoClassDefFoundError: org/apache/http/ssl/TrustStrategy
	at com.codeborne.selenide.commands.DownloadFile.<init>(DownloadFile.java:21)
	at com.codeborne.selenide.commands.Commands.addFileCommands(Commands.java:106)
	at com.codeborne.selenide.commands.Commands.resetDefaults(Commands.java:32)
	at com.codeborne.selenide.commands.Commands.<init>(Commands.java:17)
	at com.codeborne.selenide.commands.Commands.<clinit>(Commands.java:12)
       ...
Caused by: java.lang.ClassNotFoundException: org.apache.http.ssl.TrustStrategy
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 33 more
```

**Comment by asolntsev** [comment]
Fixed in Selenide 3.10
