### ISSUE TITLE
java.lang.IllegalArgumentException: Unknown Selenide method: toString

### ISSUE THREAD

**Issue by kkochetov** [codeborne/selenide#417]
Hi.
I migrete to selenide 4.0 from 3.10 and cautch this exception, when trying $$().shouldHaveSize()
In my case -- .shouldHaveSize() failed.

`java.lang.IllegalArgumentException: Unknown Selenide method: toString
	at com.codeborne.selenide.commands.Commands.execute(Commands.java:137)
	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:54)
	at com.sun.proxy.$Proxy15.toString(Unknown Source)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at com.codeborne.selenide.ElementsCollection.elementsToString(ElementsCollection.java:227)
	at com.codeborne.selenide.ex.ListSizeMismatch.<init>(ListSizeMismatch.java:16)
	at com.codeborne.selenide.collections.ListSize.fail(ListSize.java:24)
	at com.codeborne.selenide.ElementsCollection.waitUntil(ElementsCollection.java:109)
	at com.codeborne.selenide.ElementsCollection.should(ElementsCollection.java:59)
	at com.codeborne.selenide.ElementsCollection.shouldHave(ElementsCollection.java:50)
	at com.codeborne.selenide.ElementsCollection.shouldHaveSize(ElementsCollection.java:35)
	at test.Playkey.CatalogTest.autoload_games_test(CatalogTest.java:208)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:74)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)`

**Comment by asolntsev** [comment]
Bad :(

It seems to be a bug, the same as here: https://uploads.disquscdn.com/images/265d9d86eb11075bbaf7e4954f9883bd2a1f25e62ab8056484ddddab2b006baf.png

I must fix it asap.

**Comment by asolntsev** [comment]
@kkochetov I cannot reproduce the issue. Don't you have a code that manipulates with `com.codeborne.selenide.commands.Commands`? 

Please provide the code that reproduces the problem.

**Comment by kkochetov** [comment]
It`s all my fault. I (and my maven) has two selenides (3.10 and 4.0) in classpatch.
After cleanup exception gone.

**Comment by asolntsev** [comment]
Thank you for sharing information. It seems that Selenide code still needs to be improved. Selenide should throw this error immediately instead of hiding it and reporting another error.
