### ISSUE TITLE
@AndroidFindBy, @iOSFindBy doesn't work correctly with selenide

### ISSUE THREAD

**Issue by dmlemeshko** [codeborne/selenide#448]
@FindBy annotation works correctly in my example, but @AndroidFindBy failed and selenide is trying to use `name` strategy instead.
Since selenide supports `MobileBy` (e.g. `$(MobileBy.AccessibilityId("saveBtn")).click()`) it will be good to support mobile annotations as well. @asolntsev is it way to make it work? Will appreciate any ideas

Selenide version: _4.2_
Appium Java client version: _4.1.2_

Code:
_PageObject_
```
@Component
@Scope("cucumber-glue")
public class SaveAndTransferScreen {

    //@FindBy(xpath= "//*[@text='Move to a new phone']")
    @AndroidFindBy(xpath= "//*[@text='Move to a new phone']")
    public SelenideElement moveToNewPhone;

    public void moveToNewPhone() {
        moveToNewPhone.click();
    }
}
```
_Step_
```
    @When("^I select Move to a new phone")
    public void moveToNewPhone(){
        page(SaveAndTransferScreen.class).moveToNewPhone();
    }
```

stacktrace:
```
org.openqa.selenium.InvalidSelectorException: Locator Strategy 'name' is not supported for this session (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 7 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/invalid_selector_exception.html
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: '192.168.100.4', ip: '192.168.100.4', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.8.0_60'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{app=/Users/dmle1/git/e2e_test/target/test-classes/tst-TeliaMinMobil-v1.12.0.257-build413.apk, appPackage=com.halebop.servicetips.tst, networkConnectionEnabled=true, warnings={}, appWaitPackage=com.halebop.servicetips.tst, appWaitActivity=com.halebop.servicetips.activity.LoginActivity, databaseEnabled=false, deviceName=YT910WS1FT, platform=LINUX, deviceUDID=YT910WS1FT, appActivity=com.halebop.servicetips.activity.LoginActivity, desired={app=/Users/dmle1/git/e2e_test/target/test-classes/tst-TeliaMinMobil-v1.12.0.257-build413.apk, platformVersion=6.0, automationName=Appium, browserName=, platformName=Android, deviceName=Android}, platformVersion=6.0.1, webStorageEnabled=false, locationContextEnabled=false, automationName=Appium, takesScreenshot=true, browserName=, javascriptEnabled=true, platformName=Android}]
Session ID: a414e0c8-0529-483c-9126-68063c693056
*** Element info: {Using=name, value=moveToNewPhone}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:40)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:363)
	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:56)
	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.findElement(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByName(RemoteWebDriver.java:461)
	at io.appium.java_client.DefaultGenericMobileDriver.findElementByName(DefaultGenericMobileDriver.java:104)
	at io.appium.java_client.AppiumDriver.findElementByName(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.findElementByName(AndroidDriver.java:1)
	at org.openqa.selenium.By$ByName.findElement(By.java:303)
	at org.openqa.selenium.support.ByIdOrName.findElement(ByIdOrName.java:50)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:355)
	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:52)
	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.findElement(AndroidDriver.java:1)
	at com.codeborne.selenide.impl.WebElementSelector.findElement(WebElementSelector.java:28)
	at com.codeborne.selenide.impl.ElementFinder.getWebElement(ElementFinder.java:56)
	at com.codeborne.selenide.impl.WebElementSource.checkCondition(WebElementSource.java:44)
	at com.codeborne.selenide.impl.WebElementSource.findAndAssertElementIsVisible(WebElementSource.java:72)
	at com.codeborne.selenide.commands.Click.execute(Click.java:14)
	at com.codeborne.selenide.commands.Click.execute(Click.java:11)
	at com.codeborne.selenide.commands.Commands.execute(Commands.java:140)
	at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:86)
	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:62)
	at com.sun.proxy.$Proxy28.click(Unknown Source)
	at com.ebuilder.qa.screens.SaveAndTransferScreen.moveToNewPhone(SaveAndTransferScreen.java:25)
	at com.ebuilder.qa.stepdefs.SecureStepDefs.move_to_newPhone(SecureStepDefs.java:50)
	at ?.And I select Move to a new phone(src/test/resources/features/Secure.feature:11)
```

**Comment by dmlemeshko** [comment]
@asolntsev @vinogradoff any thoughts on this one?

**Comment by asolntsev** [comment]
@dmlemeshko This is a good initiative. We want to support Appium (and any other framework as well). 

But how exactly can we implement it? Can you help?
I have found such a code snippet:

```java
PageFactory.initElements(new AppiumFieldDecorator(driver,
                        IMPLICIT_WAIT,
                        TimeUnit.SECONDS),
                this
        );
```

Is it correct? Will it help? We could probably built it into Selenide...

**Comment by rosolko** [comment]
If needed reopen this issue in [selenide-appium ](https://github.com/codeborne/selenide-appium) project
