### ISSUE TITLE
Using toString() on SelenideElement while using Android driver causes exceptions 

### ISSUE THREAD

**Issue by dkorobtsov** [codeborne/selenide#494]
It seems that once again issues are caused by attempts to execute JavaScript on Android.

There are 2 problems: 
1. it's not possible to use toString() at all.
2. all tests where SelenideElement is used will fail anyway because of IDEATestNGRemoteListener exeptions.

Basically I tried to found out what will happen if I'll change all fields in all Page Objects from
private By pageObjectField;
to
private SelenideElement pageObjectField;
Expected result: PROFIT!
Actual result: :) got ~100 different exceptions...

Per my perception, problem is here:
```
package com.codeborne.selenide.impl;
public class Describe 

  private Describe appendAllAttributes() {
    Map<String, String> map = **executeJavaScript(**
        "var s = {};" +
            "var attrs = arguments[0].attributes;" +
            "for (var i = 0; i < attrs.length; i++) {" +
            "   var a = attrs[i]; " +
            "   if (a.name != 'style') {" +
            "     s[a.name] = a.value;" +
            "   }" +
            "}" +
            "return s;", element);
```

Logs are full of exceptions like:

java.lang.UnsupportedOperationException: You must be using an underlying instance of WebDriver that supports executing javascript

	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:523)
	at com.codeborne.selenide.Selenide.executeJavaScript(Selenide.java:445)
	at com.codeborne.selenide.impl.Describe.appendAllAttributes(Describe.java:28)
	at com.codeborne.selenide.impl.Describe.appendAttributes(Describe.java:24)
	at com.codeborne.selenide.impl.Describe.describe(Describe.java:97)
	at com.codeborne.selenide.commands.ToString.execute(ToString.java:15)
	at com.codeborne.selenide.commands.ToString.execute(ToString.java:11)
	at com.codeborne.selenide.commands.Commands.execute(Commands.java:140)
	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:54)
	at com.sun.proxy.$Proxy58.toString(Unknown Source)

	at java.lang.String.valueOf(String.java:2994) <---
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at org.testng.IDEATestNGRemoteListener.getParamsString(IDEATestNGRemoteListener.java:260)
	at org.testng.IDEATestNGRemoteListener.onTestStart(IDEATestNGRemoteListener.java:134)
	at org.testng.IDEATestNGRemoteListener.onTestFailure(IDEATestNGRemoteListener.java:207)
	at org.testng.IDEATestNGRemoteListener.onTestFailure(IDEATestNGRemoteListener.java:107)
	at org.testng.IDEATestNGTestListener.onTestFailure(IDEATestNGTestListener.java:34)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1895)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1879)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:778)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

P.S. btw, is casting of SelenideElement to By a supported scenario? Causes exceptions as well... basically, I would prefer to avoid casting, but it looks that it's absolutely impossible to use SelenideElement on Android at the moment.

**Comment by dkorobtsov** [comment]
So, basically, because of JavaScript execution in toString method on SelenideElement exceptions are thrown on Android when following actions are used:
adding SelenideElement to array, casting, any logging actions, impossible to use in test methods
(btw, it can be easily used like this:
SelenideElement se = $(By.id("elementid"));
se.click()
but more complicated actions where proxy is called are all causing exceptions.

**Comment by dkorobtsov** [comment]
Tested. Issue is resolved.
