### ISSUE TITLE
Screenshot for element is giving image==null

### ISSUE THREAD

**Issue by sukhjindersukh** [codeborne/selenide#499]
File f =$(By.xpath(".//*[@id='recent-work']")).screenshot();
I am using this method to get element screenshot but I am getting following error:

java.lang.IllegalArgumentException: image == null!
	at javax.imageio.ImageTypeSpecifier.createFromRenderedImage(Unknown Source)
	at javax.imageio.ImageIO.getWriter(Unknown Source)
	at javax.imageio.ImageIO.write(Unknown Source)
	at com.codeborne.selenide.impl.ScreenShotLaboratory.takeScreenshot(ScreenShotLaboratory.java:101)
	at com.codeborne.selenide.Screenshots.takeScreenShot(Screenshots.java:39)
	at com.codeborne.selenide.commands.TakeScreenshot.execute(TakeScreenshot.java:13)
	at com.codeborne.selenide.commands.TakeScreenshot.execute(TakeScreenshot.java:10)
	at com.codeborne.selenide.commands.Commands.execute(Commands.java:140)
	at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:86)
	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:62)
	at com.sun.proxy.$Proxy5.screenshot(Unknown Source)
	at testingxperts.web.tests.TC_091.test(TC_091.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)

**Comment by BorisOsipov** [comment]
Hi @sukhjindersukh 

Thank you for reporting this issue.
Could you please provide additional logs that's written before error occurs? 
I guess it describes actual reason of this error.

**Comment by rosolko** [comment]
@sukhjindersukh Can you please provide info?

**Comment by rosolko** [comment]
Feel free to reopen with additional information.
