### ISSUE TITLE
Sometimes `$.download()` fails

### ISSUE THREAD

**Issue by asolntsev** [codeborne/selenide#510]
... with error `NoSuchWindowException`.

See full stack trace:

```java
Element not found {#btn-print-payment}
Expected: exist
Screenshot: ...
Timeout: 4 s.
Caused by: NoSuchWindowException: no such window
	at com.codeborne.selenide.impl.WebElementSource.createElementNotFoundError(WebElementSource.java:31)
	at com.codeborne.selenide.impl.ElementFinder.createElementNotFoundError(ElementFinder.java:82)
	at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:115)
	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:62)
	at com.sun.proxy.$Proxy123.download(Unknown Source)
```

**Comment by asolntsev** [comment]
Fixed in Selenide 4.4.2
