### ISSUE TITLE
trim in com.codeborne.selenide.Condition.getAttributeValue(WebElement, String) is problematic for exactValue

### ISSUE THREAD

**Issue by mseele** [codeborne/selenide#573]
Hi,

i want to test that my textarea field has a whitespace at the end. 
Because of the "attr.trim()" in com.codeborne.selenide.Condition.getAttributeValue(WebElement, String) this is not possible.

When i test

dialog.description().shouldHave(exactValue("Regression test description "));

i always get following exception:

Element should have attribute value=Regression test description  {By.id: dmm-uid-dialog_edit_description}
Element: '<textarea class="gwt-TextArea BBI4CJC-a-O" id="dmm-uid-dialog_edit_description" type="textarea" value="Regression test description "></textarea>'
Screenshot: file:/C:/dev/workspaces/dmm/dmmRegressionTests/build/reports/tests/1500282739757.3.png
Timeout: 4 s.
	at com.codeborne.selenide.impl.WebElementSource.checkCondition(WebElementSource.java:66)
	at com.codeborne.selenide.commands.Should.should(Should.java:35)
	at com.codeborne.selenide.commands.Should.execute(Should.java:29)
	at com.codeborne.selenide.commands.Should.execute(Should.java:12)
	at com.codeborne.selenide.commands.Commands.execute(Commands.java:143)
	at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:87)
	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:63)
	at com.sun.proxy.$Proxy8.shouldHave(Unknown Source)
	at de.guhsoft.dmm.tests.ui.pages.AbstractElementDialog$TextField.shouldBe(AbstractElementDialog.java:48)
	at de.guhsoft.dmm.tests.ui.EntityTest.createAndEditProposals(EntityTest.java:336)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

In my opinion com.codeborne.selenide.Condition.exactValue(String) should be very strict and do not use trim(). The com.codeborne.selenide.Condition.value(String) can do this.

**Comment by asolntsev** [comment]
I agree. "$.exactValue()" should be EXACT. Can you prepare a pull request
for fixing it?

**Comment by mseele** [comment]
I've added pull request #578
