### ISSUE TITLE
Firefox browser start-up failure.

### ISSUE THREAD

**Issue by gaponte1985** [codeborne/selenide#583]
I am trying to open a browser using Firefox and navigate to yahoo.com, however when the browser is opened is not going to yahoo.com  

import static com.codeborne.selenide.Selenide.*;
import java.io.IOException;

public class example {

    public static void main(String args[]) throws IOException
    {

        System.setProperty("selenide.browser", "Firefox");
        System.setProperty("webdriver.gecko.driver", "C:\\geckodriver-v0.18.0-win64\\geckodriver.exe");
        open("http://www.yahoo.com");
    }

}

**Comment by gaponte1985** [comment]
Exception in thread "main" org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'CPX-AJ3J0WJEOTK', ip: '10.237.28.19', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: FirefoxDriver
selenide.url: http://www.google.com
selenide.baseUrl: http://localhost:8080
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:658)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:250)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:236)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:137)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:191)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:108)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:137)
	at com.codeborne.selenide.webdriver.WebDriverFactory.createFirefoxDriver(WebDriverFactory.java:191)
	at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:50)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.createDriver(WebDriverThreadLocalContainer.java:242)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.getAndCheckWebDriver(WebDriverThreadLocalContainer.java:113)
	at com.codeborne.selenide.WebDriverRunner.getAndCheckWebDriver(WebDriverRunner.java:136)
	at com.codeborne.selenide.impl.Navigator.navigateToAbsoluteUrl(Navigator.java:69)
	at com.codeborne.selenide.impl.Navigator.open(Navigator.java:32)
	at com.codeborne.selenide.Selenide.open(Selenide.java:79)
	at com.codeborne.selenide.Selenide.open(Selenide.java:53)
	at example.main(example.java:13)
Caused by: java.lang.NullPointerException
	at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:192)
	at org.openqa.selenium.firefox.XpiDriverService.start(XpiDriverService.java:94)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:78)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
	... 16 more

**Comment by gaponte1985** [comment]
selenide 4.5.1
Selenium 3.4
Firefox 54
Windows 10

**Comment by tocumarian** [comment]
maybe you should use "selenide.browser" marionette?

**Comment by gaponte1985** [comment]
Yes, Thanks, I saw this after this post, but now getting a new error is opening and going to the url  but I am getting the follow error

[GFX1-]: Receive IPC close with reason=AbnormalShutdown
Exception in thread "Thread-4" java.lang.NoClassDefFoundError: com/sun/jna/platform/win32/Kernel32
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.openqa.selenium.os.ProcessUtils.getProcessId(ProcessUtils.java:184)
	at org.openqa.selenium.os.ProcessUtils.killWinProcess(ProcessUtils.java:128)
	at org.openqa.selenium.os.ProcessUtils.killProcess(ProcessUtils.java:81)
	at org.openqa.selenium.os.UnixProcess$SeleniumWatchDog.destroyHarder(UnixProcess.java:246)
	at org.openqa.selenium.os.UnixProcess$SeleniumWatchDog.access$200(UnixProcess.java:200)
	at org.openqa.selenium.os.UnixProcess.destroy(UnixProcess.java:126)
	at org.openqa.selenium.os.CommandLine.destroy(CommandLine.java:153)
	at org.openqa.selenium.remote.service.DriverService.stop(DriverService.java:221)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:94)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:694)
	at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:533)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer$CloseBrowser.run(WebDriverThreadLocalContainer.java:179)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.sun.jna.platform.win32.Kernel32
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 26 more

**Comment by BorisOsipov** [comment]
Hi @gaponte1985 

can you share your pom.xml\build.gradle file? 
It looks like you have some dependencies with wrong scope.

**Comment by asolntsev** [comment]
Hi @gaponte1985!
Please upgrade to Selenide 4.8 - it now downloads webdriver binary automatically. Probably your problem is already solved.

**Comment by rosolko** [comment]
@gaponte1985 Update to latest version and feel free to reopen with additional info if needed.
