### ISSUE TITLE
Not running Chrome browser

### ISSUE THREAD

**Issue by BabyRoot** [codeborne/selenide#612]
## The problem
Update on new version Selenide 4.7. And Chrome not run.
FF run succes.

## Details
If set Chrome - browser not run:

> 
> TEST STARTED: 03. лалалал
> STEP [17:20:50]: loginUser[test_user:test_user]
> окт 02, 2017 5:20:50 PM com.codeborne.selenide.impl.WebDriverThreadLocalContainer getWebDriver
> INFO: No webdriver is bound to current thread: 1 - let's create new webdriver
> STEP [17:20:51]  --------------------------- end
> Starting ChromeDriver 2.32.498550 (9dec58e66c31bcc53a9ce3c7226f0c1c5810906a) on port 18849
> Only local connections are allowed.
> окт 02, 2017 5:20:52 PM com.codeborne.selenide.impl.WebDriverThreadLocalContainer getWebDriver
> INFO: No webdriver is bound to current thread: 1 - let's create new webdriver
> Starting ChromeDriver 2.32.498550 (9dec58e66c31bcc53a9ce3c7226f0c1c5810906a) on port 7984
> Only local connections are allowed.
> окт 02, 2017 5:20:53 PM com.codeborne.selenide.impl.WebDriverThreadLocalContainer getWebDriver
> INFO: No webdriver is bound to current thread: 1 - let's create new webdriver
> Starting ChromeDriver 2.32.498550 (9dec58e66c31bcc53a9ce3c7226f0c1c5810906a) on port 48274
> Only local connections are allowed.
> 
> Results:
> 
> Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
> 
> There are test failures.
> 
> Please refer to C:\lalalal\target\surefire-reports for the individual test results.
> Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
> There was an error in the forked process
> NoSuchMethodError: com.google.common.util.concurrent.SimpleTimeLimiter.create(Ljava/util/concurrent/ExecutorService;)Lcom/google/common/util/concurrent/SimpleTimeLimiter;
> org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
> NoSuchMethodError: com.google.common.util.concurrent.SimpleTimeLimiter.create(Ljava/util/concurrent/ExecutorService;)Lcom/google/common/util/concurrent/SimpleTimeLimiter;
> 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:665)
> 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
> 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:279)
> 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:243)
> 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1077)
> 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:907)
> 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:785)
> 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
> 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
> 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
> 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
> 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
> 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
> 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
> 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
> 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
> 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
> 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
> 

## Tell us about your environment
* **Selenide Version:** 4.7
* **Chrome:**  61.0.3163.100 (Официальная сборка), (64 бит) 
* **Browser Driver Version:** ChromeDriver 2.32
* **OS Version:** Win 10

**Comment by BorisOsipov** [comment]
Looks like guava dependency issue. @BabyRoot can you share your pom.xml?

**Comment by asolntsev** [comment]
@BabyRoot Yes, it's a Maven dependency issue. Maven downloads the latest guava 23.0, but selenium 3.5.3 works only with guava 22.0

One simple solution is to declare guava 22.0 dependency explicitly in your pom.xml

**Comment by BabyRoot** [comment]
Yes, thanks, the problem was solved.
