### ISSUE TITLE
Selenide + Selenium 3.6 displayed stack trace of NoClassDefFoundError

### ISSUE THREAD

**Issue by kazuki43zoo** [codeborne/selenide#616]
## The problem
I've tried Selenide 4.7.1 + Selenium 3.6.0. All tests are the success, However following stack trace is displayed.

```
...
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 29.279 s - in com.kazuki43zoo.jpetstore.JpetstoreApplicationTests
16:20:43.400 [Thread-4] INFO  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - Closing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@471a9022: startup date [Fri Oct 06 16:20:18 JST 2017]; root of context hierarchy
16:20:43.400 [Thread-6] INFO  c.c.s.i.WebDriverThreadLocalContainer - Close webdriver: 1 -> org.openqa.selenium.htmlunit.HtmlUnitDriver@fa11fda
Exception in thread "Thread-54" java.lang.NoClassDefFoundError: org/openqa/selenium/internal/Killable
        at com.codeborne.selenide.impl.WebDriverThreadLocalContainer$CloseBrowser.killBrowser(WebDriverThreadLocalContainer.java:199)
        at com.codeborne.selenide.impl.WebDriverThreadLocalContainer$CloseBrowser.run(WebDriverThreadLocalContainer.java:189)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.internal.Killable
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 3 more
16:20:43.427 [Thread-4] INFO  com.zaxxer.hikari.HikariDataSource - testdb - Shutdown initiated...
16:20:43.432 [Thread-4] INFO  com.zaxxer.hikari.HikariDataSource - testdb - Shutdown completed.
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:12 min
[INFO] Finished at: 2017-10-06T16:20:44+09:00
[INFO] Final Memory: 71M/831M
[INFO] ------------------------------------------------------------------------
```

## Details
This root cause is removed the `Killable` interface since Selenium 3.6.0(it's deprecated API since 3.5.x).
See [here](https://github.com/SeleniumHQ/selenium/issues/4793#issuecomment-334061958).

## Tell us about your environment
* **Selenide Version:** 4.7.1
* **Chrome\Firefox\IE Version:** no-browser (use the HTMLUnit)
* **Browser Driver Version:** htmlunit-driver 2.27
* **Selenium Version:** 3.6.0
* **OS Version:** Mac OS X Yosemite 10.10.5

## Code To Reproduce Issue [ Good To Have ]

* https://github.com/kazuki43zoo/mybatis-spring-boot-jpetstore/tree/ci-spring-boot-2

**Comment by BorisOsipov** [comment]
Hi.
Thank you to reporting the issue. It will be fixed in https://github.com/codeborne/selenide/pull/611

**Comment by kazuki43zoo** [comment]
Thanks! I've closed because duplicated.

**Comment by sergewar** [comment]
I have the same issue with selenide 4.8 and selenium 3.6.0
But I use EventFiringWebDriver

Nov 29, 2017 3:36:41 PM com.codeborne.selenide.impl.WebDriverThreadLocalContainer closeWebDriver
INFO: Close webdriver: 1 -> org.openqa.selenium.support.events.EventFiringWebDriver@7bf185b4
[Start method] : BaseGuiSortCenterTest.tearDownGui
Nov 29, 2017 3:36:41 PM com.codeborne.selenide.impl.WebDriverThreadLocalContainer$CloseBrowser run
INFO: Trying to close the browser EventFiringWebDriver ...
Exception in thread "Thread-3" java.lang.NoClassDefFoundError: org/openqa/selenium/internal/Killable
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer$CloseBrowser.killBrowser(WebDriverThreadLocalContainer.java:199)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer$CloseBrowser.run(WebDriverThreadLocalContainer.java:189)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.internal.Killable
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more
Nov 29, 2017 3:36:41 PM com.codeborne.selenide.impl.WebDriverThreadLocalContainer closeWebDriver
INFO: Closed webdriver in 816 ms

**Comment by BorisOsipov** [comment]
@sergewar please double check your Selenide version.
You attached error stacktrace from Selenide version < 4.8

**Comment by sergewar** [comment]
Sorry. Is was my fault.
