### ISSUE TITLE
Selenide tries to decorate SelenideElement without @FindBy annotation even if it is already initialized in ElementsContainer

### ISSUE THREAD

**Issue by CaBocuk** [codeborne/selenide#617]
## The problem
Selenide tries to decorate SelenideElement without @FindBy annotation even if it is already initialized in ElementsContainer

## Details
I have SelenideElement without @FindBy which is already initialized with $(...) method. It is situated inside ElementsContainer which is declared in some page object -> then try to instantiate PO using _page(Page.class)_ or _open(url, Page.class)_ -> Selenide tries to decorate my SelenideElement despite it is already instantiated.

Similar issue was already fixed for decorating such fields which are declared directly in PO (https://github.com/codeborne/selenide/pull/443) 
It was solved by using **com.codeborne.selenide.SelenidePageFactory** instead of default **org.openqa.selenium.support.PageFactory**. 

But it wasn't changed for ElementsContainer's elements initializing in method 
**com.codeborne.selenide.impl.SelenideFieldDecorator#initElementsContainer(Class<?> type, SelenideElement self)**. 
It still uses default PageFactory.initElements(...) instead of SelenidePageFactory.initElements(...) which checks whether field is already initialized or not

## Tell us about your environment
* **Selenide Version:** 4.7.1
* **Chrome\Firefox\IE Version:** Chrome 61.0.3163.100 but I think it's not browser-dependent
* **Browser Driver Version:** Automatically downloaded by Selenide :)
* **Selenium Version:** 3.5.3
* **OS Version:** Win 10

## Code To Reproduce Issue
```
public class Tmp {

    public static void main(String... args){
        Configuration.browser = "chrome";
        Page page = Selenide.open("http://selenide.org/", Page.class);
        page.whatIsSelenideBlock.title.shouldHave(Condition.text("What is Selenide?"));
    }

    public static class Page{
        @FindBy(xpath="(//div[@class='wrapper-color-content'])[1]") // xpath is just 4 fun :)
        Block whatIsSelenideBlock;
    }

    public static class Block extends ElementsContainer{
        SelenideElement title = $("h3");
        SelenideElement arrowDown = $("img");
    }
}
```

Error log:
```
Exception in thread "main" Element not found {by id or name "title"}
Expected: text 'What is Selenide?'
Screenshot: file:/C:/Users/Artsem_Savosik/IdeaProjects/epam-events-autotests/build/reports/tests/1507303101755.0.png
Page source: file:/C:/Users/Artsem_Savosik/IdeaProjects/epam-events-autotests/build/reports/tests/1507303101755.0.html
Timeout: 4 s.
Caused by: NoSuchElementException: no such element: Unable to locate element: {"method":"name","selector":"title"}
	at com.codeborne.selenide.impl.WebElementSource.createElementNotFoundError(WebElementSource.java:31)
	at com.codeborne.selenide.impl.ElementFinder.createElementNotFoundError(ElementFinder.java:82)
	at com.codeborne.selenide.impl.WebElementSource.checkCondition(WebElementSource.java:59)
	at com.codeborne.selenide.commands.Should.should(Should.java:35)
	at com.codeborne.selenide.commands.Should.execute(Should.java:29)
	at com.codeborne.selenide.commands.Should.execute(Should.java:12)
	at com.codeborne.selenide.commands.Commands.execute(Commands.java:143)
	at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:87)
	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:63)
	at com.sun.proxy.$Proxy4.shouldHave(Unknown Source)
	at com.epam.events.common.run.Tmp.main(Tmp.java:13)
```

**Comment by asolntsev** [comment]
Fix by PR https://github.com/codeborne/selenide/pull/618. Will be released in Selenide 4.9
