### ISSUE TITLE
Selenide throws NullPointerException if reportFolder is null

### ISSUE THREAD

**Issue by asolntsev** [codeborne/selenide#804]
## The problem
Selenide throws NullPointerException if reportFolder is null.
Instead, it should report a clear error message and continue without saving screenshot.

## Details
Here is stack trace:

```
java.lang.NullPointerException
    at com.codeborne.selenide.impl.ScreenShotLaboratory.ensureFolderExists(ScreenShotLaboratory.java:144)
    at com.codeborne.selenide.impl.ScreenShotLaboratory.copyFile(ScreenShotLaboratory.java:344)
    at com.codeborne.selenide.impl.ScreenShotLaboratory.writeToFile(ScreenShotLaboratory.java:357)
    at com.codeborne.selenide.impl.ScreenShotLaboratory.savePageSourceToFile(ScreenShotLaboratory.java:319)
    at com.codeborne.selenide.impl.ScreenShotLaboratory.savePageSourceToFile(ScreenShotLaboratory.java:294)
    at com.codeborne.selenide.impl.ScreenShotLaboratory.takeScreenShot(ScreenShotLaboratory.java:80)
    at com.codeborne.selenide.impl.ScreenShotLaboratory.takeScreenShot(ScreenShotLaboratory.java:60)
    at com.codeborne.selenide.impl.ScreenShotLaboratory.formatScreenShotPath(ScreenShotLaboratory.java:398)
    at com.sun.proxy.$Proxy8.shouldHave(Unknown Source)
    at some.SomeTest.someClick
```

## Tell us about your environment
* **Selenide Version: 4.12 - 4.14.1**

## Code To Reproduce Issue [ Good To Have ]
```
Configuration.reportsFolder = null;
open("https://google.com");
$("blah").should(exist);
```

**Comment by asolntsev** [comment]
Fixed by https://github.com/codeborne/selenide/pull/805
